In [2]:
url="https://s3.us-east-2.amazonaws.com/datafaculty/bootcamp/HR_comma_sep.csv"

In [4]:
import pandas as pd

In [6]:
import numpy as np

In [10]:
data=pd.read_csv(url)

In [13]:
data.head(3)

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium

In [15]:
data.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
sales                    0
salary                   0
dtype: int64

In [17]:
data=pd.get_dummies(data)

In [19]:
import sklearn.model_selection as model_selection

In [21]:
y=data['left']
x=data.drop('left',axis=1)

In [23]:
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,y,test_size=0.2,random_state=200)

In [28]:
import sklearn.ensemble as ensemble

In [27]:
clf=ensemble.RandomForestClassifier()

In [32]:
clf=ensemble.RandomForestClassifier(n_estimators=100,oob_score=True,n_jobs=-1)

In [34]:
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [36]:
clf.predict(x_test)

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [38]:
clf.predict_proba(x_test)[:,1]

array([0.  , 0.01, 0.01, ..., 0.01, 0.17, 1.  ])

In [40]:
clf.feature_importances_

array([0.32763843, 0.12130802, 0.16470965, 0.15368401, 0.18316819,
       0.01000534, 0.00163319, 0.00164304, 0.00161967, 0.00153327,
       0.00151157, 0.00145985, 0.00143451, 0.00126713, 0.00350672,
       0.00305507, 0.00379398, 0.00599848, 0.00751496, 0.00351494])

In [43]:
pd.Series(clf.feature_importances_,index=x_train.columns).sort_values(ascending=False)

satisfaction_level       0.327638
time_spend_company       0.183168
number_project           0.164710
average_montly_hours     0.153684
last_evaluation          0.121308
Work_accident            0.010005
salary_low               0.007515
salary_high              0.005998
sales_technical          0.003794
salary_medium            0.003515
sales_sales              0.003507
sales_support            0.003055
sales_IT                 0.001643
promotion_last_5years    0.001633
sales_RandD              0.001620
sales_accounting         0.001533
sales_hr                 0.001512
sales_management         0.001460
sales_marketing          0.001435
sales_product_mng        0.001267
dtype: float64

In [45]:
clf.oob_score_

0.9903325277106425

In [49]:
## If 100,200, or 300 times is better
for i in [100,200,300]:
    clf=ensemble.RandomForestClassifier(n_estimators=i,oob_score=True,n_jobs=-1)
    clf.fit(x_train,y_train)
    print("oob score for {} trees is {}".format(i,clf.oob_score_))

oob score for 100 trees is 0.9904992082673556
oob score for 200 trees is 0.9908325693807817
oob score for 300 trees is 0.9906658888240687


In [50]:
# Get prob predictions on oob data

In [51]:
clf.oob_decision_function_[:,1]

array([1.        , 1.        , 0.        , ..., 0.97142857, 0.        ,
       0.92      ])

In [53]:
pred_oob=clf.oob_decision_function_[:,1]

In [1]:
import sklearn .metrics as metrics

In [58]:
metrics.roc_auc_score(y_train,pred_oob)

0.9935382438633601

In [60]:
## If 100,200, or 300 times is better
for i in [100,200,300]:
    clf=ensemble.RandomForestClassifier(n_estimators=i,oob_score=True,n_jobs=-1)
    clf.fit(x_train,y_train)
    pred_oob=clf.oob_decision_function_[:,1]
    auc=metrics.roc_auc_score(y_train,pred_oob)
    print("Auc for {} trees is {}".format(i,auc))
    

Auc for 100 trees is 0.9916685259847509
Auc for 200 trees is 0.9942571070724124
Auc for 300 trees is 0.9926837446258481
