In [105]:
url="https://s3.us-east-2.amazonaws.com/datafaculty/bootcamp/membership.csv"

In [107]:
import pandas as pd
import numpy as np

In [108]:
data=pd.read_csv(url)

In [109]:
data.head()

MEMBERSHIP_NUMBER  MEMBERSHIP_TERM_YEARS  ANNUAL_FEES MEMBER_MARITAL_STATUS  \
0            A00001                     29     113125.0                     M   
1            A00002                     38     112220.0                     M   
2            A00003                     12     100000.0                     M   
3            A00004                     12     100000.0                     M   
4            A00005                     46     100000.0                     M   

  MEMBER_GENDER  MEMBER_ANNUAL_INCOME  MEMBER_OCCUPATION_CD  \
0             M            25200000.0                   1.0   
1             M            10339200.0                   1.0   
2             M            14400000.0                   1.0   
3             M             9000000.0                   1.0   
4             M             4800000.0                   1.0   

  MEMBERSHIP_PACKAGE  MEMBER_AGE_AT_ISSUE  ADDITIONAL_MEMBERS PAYMENT_MODE  \
0             TYPE-B                   45                   2       ANNUAL   
1             TYPE-B                   36                   3    QUARTERLY   
2             TYPE-B                   42                   1       ANNUAL   
3             TYPE-B                   39                   2       ANNUAL   
4             TYPE-B                   27                   2    QUARTERLY   

  AGENT_CODE MEMBERSHIP_STATUS  START_DATE (YYYYMMDD)  END_DATE  (YYYYMMDD)  
0        477           INFORCE               20060914                   NaN  
1        255           INFORCE               20061102                   NaN  
2       7866           INFORCE               20070124                   NaN  
3     200533           INFORCE               20070122                   NaN  
4       6988           INFORCE               20070131                   NaN

In [110]:
data=data.drop(['MEMBERSHIP_NUMBER','AGENT_CODE'],axis=1)

In [111]:
data.head()

MEMBERSHIP_TERM_YEARS  ANNUAL_FEES MEMBER_MARITAL_STATUS MEMBER_GENDER  \
0                     29     113125.0                     M             M   
1                     38     112220.0                     M             M   
2                     12     100000.0                     M             M   
3                     12     100000.0                     M             M   
4                     46     100000.0                     M             M   

   MEMBER_ANNUAL_INCOME  MEMBER_OCCUPATION_CD MEMBERSHIP_PACKAGE  \
0            25200000.0                   1.0             TYPE-B   
1            10339200.0                   1.0             TYPE-B   
2            14400000.0                   1.0             TYPE-B   
3             9000000.0                   1.0             TYPE-B   
4             4800000.0                   1.0             TYPE-B   

   MEMBER_AGE_AT_ISSUE  ADDITIONAL_MEMBERS PAYMENT_MODE MEMBERSHIP_STATUS  \
0                   45                   2       ANNUAL           INFORCE   
1                   36                   3    QUARTERLY           INFORCE   
2                   42                   1       ANNUAL           INFORCE   
3                   39                   2       ANNUAL           INFORCE   
4                   27                   2    QUARTERLY           INFORCE   

   START_DATE (YYYYMMDD)  END_DATE  (YYYYMMDD)  
0               20060914                   NaN  
1               20061102                   NaN  
2               20070124                   NaN  
3               20070122                   NaN  
4               20070131                   NaN

In [112]:
data.columns

Index(['MEMBERSHIP_TERM_YEARS', 'ANNUAL_FEES', 'MEMBER_MARITAL_STATUS',
       'MEMBER_GENDER', 'MEMBER_ANNUAL_INCOME', 'MEMBER_OCCUPATION_CD',
       'MEMBERSHIP_PACKAGE', 'MEMBER_AGE_AT_ISSUE', 'ADDITIONAL_MEMBERS',
       'PAYMENT_MODE', 'MEMBERSHIP_STATUS', 'START_DATE (YYYYMMDD)',
       'END_DATE  (YYYYMMDD)'],
      dtype='object')

In [113]:
data=data.drop(['START_DATE (YYYYMMDD)','END_DATE  (YYYYMMDD)'],axis=1)

In [114]:
data.columns

Index(['MEMBERSHIP_TERM_YEARS', 'ANNUAL_FEES', 'MEMBER_MARITAL_STATUS',
       'MEMBER_GENDER', 'MEMBER_ANNUAL_INCOME', 'MEMBER_OCCUPATION_CD',
       'MEMBERSHIP_PACKAGE', 'MEMBER_AGE_AT_ISSUE', 'ADDITIONAL_MEMBERS',
       'PAYMENT_MODE', 'MEMBERSHIP_STATUS'],
      dtype='object')

In [14]:
data.isnull().sum()

MEMBERSHIP_TERM_YEARS       0
ANNUAL_FEES                 0
MEMBER_MARITAL_STATUS    2597
MEMBER_GENDER             611
MEMBER_ANNUAL_INCOME     1754
MEMBER_OCCUPATION_CD       43
MEMBERSHIP_PACKAGE          0
MEMBER_AGE_AT_ISSUE         0
ADDITIONAL_MEMBERS          0
PAYMENT_MODE                0
MEMBERSHIP_STATUS           0
dtype: int64

In [115]:
data['MEMBER_MARITAL_STATUS'].value_counts()

M    6430
S    1144
W     146
D      45
Name: MEMBER_MARITAL_STATUS, dtype: int64

In [116]:
data['MEMBER_MARITAL_STATUS']=data['MEMBER_MARITAL_STATUS'].fillna('Missing')

In [117]:
data['MEMBER_GENDER']=data['MEMBER_GENDER'].fillna("Missing")

In [118]:
data['MEMBER_OCCUPATION_CD'].unique()

array([ 1.,  4.,  5.,  6., nan,  2.,  3.])

In [119]:
data['MEMBER_OCCUPATION_CD'].value_counts()

1.0    7281
2.0    1778
6.0     728
5.0     324
4.0     207
3.0       1
Name: MEMBER_OCCUPATION_CD, dtype: int64

In [120]:
ind_m=data[data['MEMBER_OCCUPATION_CD'].isnull()].index

In [121]:
data.shape

(10362, 11)

In [122]:
data=data.drop(ind_m,axis=0)

In [123]:
data.isnull().sum()

MEMBERSHIP_TERM_YEARS       0
ANNUAL_FEES                 0
MEMBER_MARITAL_STATUS       0
MEMBER_GENDER               0
MEMBER_ANNUAL_INCOME     1730
MEMBER_OCCUPATION_CD        0
MEMBERSHIP_PACKAGE          0
MEMBER_AGE_AT_ISSUE         0
ADDITIONAL_MEMBERS          0
PAYMENT_MODE                0
MEMBERSHIP_STATUS           0
dtype: int64

In [124]:
data['MEMBER_ANNUAL_INCOME'].describe()

count    8.589000e+03
mean     1.451762e+06
std      1.759114e+07
min      9.996000e+03
25%      3.999960e+05
50%      5.499960e+05
75%      9.999960e+05
max      1.000000e+09
Name: MEMBER_ANNUAL_INCOME, dtype: float64

In [125]:
data['MEMBER_ANNUAL_INCOME']=data['MEMBER_ANNUAL_INCOME'].fillna(5.499960e+05)

In [23]:
data.isnull().sum()

MEMBERSHIP_TERM_YEARS    0
ANNUAL_FEES              0
MEMBER_MARITAL_STATUS    0
MEMBER_GENDER            0
MEMBER_ANNUAL_INCOME     0
MEMBER_OCCUPATION_CD     0
MEMBERSHIP_PACKAGE       0
MEMBER_AGE_AT_ISSUE      0
ADDITIONAL_MEMBERS       0
PAYMENT_MODE             0
MEMBERSHIP_STATUS        0
dtype: int64

In [126]:
## Label encode categorical variables
import sklearn.preprocessing as preprocessing

In [127]:
le=preprocessing.LabelEncoder()

In [130]:
data['MEMBER_MARITAL_STATUS']=le.fit_transform(data['MEMBER_MARITAL_STATUS'])

In [32]:
data

MEMBERSHIP_TERM_YEARS  ANNUAL_FEES  MEMBER_MARITAL_STATUS  \
0                         29    113125.00                      1   
1                         38    112220.00                      1   
2                         12    100000.00                      1   
3                         12    100000.00                      1   
4                         46    100000.00                      1   
5                         12    110000.00                      2   
6                         36    100000.00                      1   
7                         12    120000.00                      1   
8                         35    120000.00                      2   
9                         33    102700.00                      1   
10                        12   1000000.00                      1   
11                        39    100000.00                      1   
12                        12    100000.00                      2   
13                        36    101350.00                      1   
14                        12    100000.00                      1   
15                        12    600000.00                      1   
16                        12    200000.00                      1   
17                        12    200000.00                      3   
18                        12    200000.00                      1   
19                        12    100000.80                      3   
20                        12    150000.00                      3   
21                        12    100000.00                      3   
22                        37    100000.00                      1   
23                        12    100000.00                      1   
24                        12    125000.00                      1   
25                        12    100000.00                      1   
26                        12    200000.00                      3   
27                        12    100000.00                      1   
28                        12    100000.00                      2   
29                        12    100000.00                      3   
...                      ...          ...                    ...   
10332                     32    241174.43                      2   
10333                     78    200000.08                      2   
10334                     81    199999.92                      2   
10335                     17    100203.48                      1   
10336                     22    110000.18                      3   
10337                     17    103090.03                      2   
10338                     22    101853.00                      1   
10339                     19    106883.76                      1   
10340                     22    299998.08                      2   
10341                     99    100560.24                      2   
10342                     22    125062.22                      3   
10343                     22    104002.50                      2   
10344                     17    136308.72                      1   
10345                     17    123712.92                      1   
10346                     17    123712.92                      1   
10347                     22    206180.01                      1   
10348                     77    274990.82                      2   
10349                     76    155000.28                      2   
10350                     59    120003.78                      1   
10351                     17    150000.21                      1   
10352                     32    297270.24                      1   
10353                     19    123706.92                      3   
10354                     17    141011.64                      1   
10355                     17    125017.09                      2   
10356                     17    113316.53                      1   
10357                     17    206180.15                      2   
10358                     22    100000.42                      

In [131]:
data['MEMBERSHIP_STATUS'].replace('INFORCE',1,inplace=True)

In [132]:
data['MEMBERSHIP_STATUS'].replace('CANCELLED',0,inplace=True)

In [143]:
data.head(3)

MEMBERSHIP_TERM_YEARS  ANNUAL_FEES  MEMBER_MARITAL_STATUS  \
0                     29     113125.0                      1   
1                     38     112220.0                      1   
2                     12     100000.0                      1   

   MEMBER_ANNUAL_INCOME  MEMBER_OCCUPATION_CD  MEMBER_AGE_AT_ISSUE  \
0            25200000.0                   1.0                   45   
1            10339200.0                   1.0                   36   
2            14400000.0                   1.0                   42   

   ADDITIONAL_MEMBERS  MEMBERSHIP_STATUS  MEMBER_GENDER_F  MEMBER_GENDER_M  \
0                   2                  1                0                1   
1                   3                  1                0                1   
2                   1                  1                0                1   

   MEMBERSHIP_PACKAGE_TYPE-B  PAYMENT_MODE_MONTHLY  PAYMENT_MODE_QUARTERLY  \
0                          1                     0                       0   
1                          1                     0                       1   
2                          1                     0                       0   

   PAYMENT_MODE_SEMI-ANNUAL  
0                         0  
1                         0  
2                         0

In [135]:
data=pd.get_dummies(data)

In [136]:
data.columns

Index(['MEMBERSHIP_TERM_YEARS', 'ANNUAL_FEES', 'MEMBER_MARITAL_STATUS',
       'MEMBER_ANNUAL_INCOME', 'MEMBER_OCCUPATION_CD', 'MEMBER_AGE_AT_ISSUE',
       'ADDITIONAL_MEMBERS', 'MEMBERSHIP_STATUS', 'MEMBER_GENDER_F',
       'MEMBER_GENDER_M', 'MEMBER_GENDER_Missing', 'MEMBERSHIP_PACKAGE_TYPE-A',
       'MEMBERSHIP_PACKAGE_TYPE-B', 'PAYMENT_MODE_ANNUAL',
       'PAYMENT_MODE_MONTHLY', 'PAYMENT_MODE_QUARTERLY',
       'PAYMENT_MODE_SEMI-ANNUAL', 'PAYMENT_MODE_SINGLE-PREMIUM'],
      dtype='object')

In [137]:
data.head(2)

MEMBERSHIP_TERM_YEARS  ANNUAL_FEES  MEMBER_MARITAL_STATUS  \
0                     29     113125.0                      1   
1                     38     112220.0                      1   

   MEMBER_ANNUAL_INCOME  MEMBER_OCCUPATION_CD  MEMBER_AGE_AT_ISSUE  \
0            25200000.0                   1.0                   45   
1            10339200.0                   1.0                   36   

   ADDITIONAL_MEMBERS  MEMBERSHIP_STATUS  MEMBER_GENDER_F  MEMBER_GENDER_M  \
0                   2                  1                0                1   
1                   3                  1                0                1   

   MEMBER_GENDER_Missing  MEMBERSHIP_PACKAGE_TYPE-A  \
0                      0                          0   
1                      0                          0   

   MEMBERSHIP_PACKAGE_TYPE-B  PAYMENT_MODE_ANNUAL  PAYMENT_MODE_MONTHLY  \
0                          1                    1                     0   
1                          1                    0                     0   

   PAYMENT_MODE_QUARTERLY  PAYMENT_MODE_SEMI-ANNUAL  \
0                       0                         0   
1                       1                         0   

   PAYMENT_MODE_SINGLE-PREMIUM  
0                            0  
1                            0

In [138]:
data=data.drop(['MEMBER_GENDER_Missing','MEMBERSHIP_PACKAGE_TYPE-A','PAYMENT_MODE_ANNUAL','PAYMENT_MODE_SINGLE-PREMIUM',],axis=1)

In [140]:
y=data['MEMBERSHIP_STATUS']
x=data.drop('MEMBERSHIP_STATUS',axis=1)

In [142]:
y.head(3)


0    1
1    1
2    1
Name: MEMBERSHIP_STATUS, dtype: int64

In [69]:
x.head(3)

MEMBERSHIP_TERM_YEARS  ANNUAL_FEES  MEMBER_MARITAL_STATUS  \
0                     29     113125.0                      1   
1                     38     112220.0                      1   
2                     12     100000.0                      1   

   MEMBER_ANNUAL_INCOME  MEMBER_OCCUPATION_CD  MEMBER_AGE_AT_ISSUE  \
0            25200000.0                   1.0                   45   
1            10339200.0                   1.0                   36   
2            14400000.0                   1.0                   42   

   ADDITIONAL_MEMBERS  MEMBER_GENDER_F  MEMBER_GENDER_M  \
0                   2                0                1   
1                   3                0                1   
2                   1                0                1   

   MEMBERSHIP_PACKAGE_TYPE-B  PAYMENT_MODE_MONTHLY  PAYMENT_MODE_QUARTERLY  \
0                          1                     0                       0   
1                          1                     0                       1   
2                          1                     0                       0   

   PAYMENT_MODE_SEMI-ANNUAL  
0                         0  
1                         0  
2                         0

In [144]:
import sklearn.model_selection as model_selection

In [145]:
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,y,test_size=0.2,random_state=200)

In [146]:
x_train.head(4)

MEMBERSHIP_TERM_YEARS  ANNUAL_FEES  MEMBER_MARITAL_STATUS  \
3737                     69    100010.00                      3   
9131                     22    120062.64                      1   
4005                     12    100000.00                      1   
5798                     12    119995.56                      1   

      MEMBER_ANNUAL_INCOME  MEMBER_OCCUPATION_CD  MEMBER_AGE_AT_ISSUE  \
3737              699996.0                   1.0                   24   
9131             1560000.0                   1.0                   60   
4005              876996.0                   1.0                   53   
5798              199992.0                   1.0                   73   

      ADDITIONAL_MEMBERS  MEMBER_GENDER_F  MEMBER_GENDER_M  \
3737                   0                0                1   
9131                   1                0                1   
4005                   2                0                1   
5798                   3                1                0   

      MEMBERSHIP_PACKAGE_TYPE-B  PAYMENT_MODE_MONTHLY  PAYMENT_MODE_QUARTERLY  \
3737                          1                     0                       0   
9131                          0                     1                       0   
4005                          1                     0                       0   
5798                          0                     1                       0   

      PAYMENT_MODE_SEMI-ANNUAL  
3737                         0  
9131                         0  
4005                         0  
5798                         0

In [147]:
y_train.head(3)



3737    1
9131    1
4005    0
Name: MEMBERSHIP_STATUS, dtype: int64

In [160]:
import sklearn.ensemble as ensemble

In [77]:
##ranfor=ensemble.RandomForestClassifier()

In [149]:
ranfor=ensemble.RandomForestClassifier(n_estimators=100,oob_score=True,n_jobs=-1)

In [151]:
ranfor.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [152]:
ranfor.predict(x_test)

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [153]:
ranfor.predict_proba(x_test)[:,1]

array([0.19, 0.46, 0.78, ..., 0.94, 0.61, 0.66])

In [157]:
for i in [100,200,300]:
    clf=ensemble.RandomForestClassifier(n_estimators=i,oob_score=True,n_jobs=-1)
    clf.fit(x_train,y_train)
    print("oob score for {} trees is {}".format(i,clf.oob_score_))

oob score for 100 trees is 0.6927922471229558
oob score for 200 trees is 0.6942459115687463
oob score for 300 trees is 0.6961841308298001


In [177]:
for j in range(10,400,30):
    ranfor=ensemble.RandomForestClassifier(n_estimators=j,oob_score=True,n_jobs=-1)
    ranfor.fit(x_train,y_train)
    oob=ranfor.oob_score_
    print("oob score for {} trees is {}".format(j,ranfor.oob_score_))

C:\Users\venus2\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\venus2\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])


oob score for 10 trees is 0.646274984857662
oob score for 40 trees is 0.6799515445184736
oob score for 70 trees is 0.6890369473046638
oob score for 100 trees is 0.6931556632344034
oob score for 130 trees is 0.6930345245305876
oob score for 160 trees is 0.6978800726832223
oob score for 190 trees is 0.6926711084191399
oob score for 220 trees is 0.6927922471229558
oob score for 250 trees is 0.6950938824954573
oob score for 280 trees is 0.698122350090854
oob score for 310 trees is 0.6961841308298001
oob score for 340 trees is 0.6961841308298001
oob score for 370 trees is 0.6977589339794065


In [154]:
ranfor.feature_importances_

array([0.1472189 , 0.16837237, 0.02628271, 0.21330304, 0.03321889,
       0.23931981, 0.0591213 , 0.01395697, 0.01423314, 0.03505273,
       0.0171619 , 0.01017906, 0.02257919])

In [155]:
ranfor.oob_score_

0.6894003634161114

In [156]:
pd.Series(ranfor.feature_importances_,index=x_train.columns).sort_values(ascending=False)

MEMBER_AGE_AT_ISSUE          0.239320
MEMBER_ANNUAL_INCOME         0.213303
ANNUAL_FEES                  0.168372
MEMBERSHIP_TERM_YEARS        0.147219
ADDITIONAL_MEMBERS           0.059121
MEMBERSHIP_PACKAGE_TYPE-B    0.035053
MEMBER_OCCUPATION_CD         0.033219
MEMBER_MARITAL_STATUS        0.026283
PAYMENT_MODE_SEMI-ANNUAL     0.022579
PAYMENT_MODE_MONTHLY         0.017162
MEMBER_GENDER_M              0.014233
MEMBER_GENDER_F              0.013957
PAYMENT_MODE_QUARTERLY       0.010179
dtype: float64

In [183]:
ranfor.oob_decision_function_[:,1]

array([0.8358209 , 0.68891491, 0.9       , ..., 0.85915493, 0.67424242,
       0.93939394])

In [184]:
pred_oob=ranfor.oob_decision_function_[:,1]

In [185]:
import sklearn .metrics as metrics

In [187]:
metrics.roc_auc_score(y_train,pred_oob)

0.696329123270431

In [191]:
for j in [160,280,370]:
    ranfor=ensemble.RandomForestClassifier(n_estimators=j,oob_score=True,n_jobs=-1)
    ranfor.fit(x_train,y_train)
    pred_oob=ranfor.oob_decision_function_[:,1]
    auc=metrics.roc_auc_score(y_train,pred_oob)
    print("Auc for {} trees is {}".format(j,auc))
    

Auc for 160 trees is 0.692925049943665
Auc for 280 trees is 0.6925401499323119
Auc for 370 trees is 0.6966131227829995


In [193]:
## Model with best estimator chosen, estimator =280
ranfor1=ensemble.RandomForestClassifier(n_estimators=280,oob_score=True,n_jobs=-1)

In [197]:
ranfor1.fit(x_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=280, n_jobs=-1,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [199]:
ranfor1.predict(x_test)

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [203]:
ranfor1.predict_proba(x_test)[:,1]

array([0.09642857, 0.45857143, 0.78928571, ..., 0.94004677, 0.57410714,
       0.63571429])

In [204]:
ranfor1.oob_score_

0.6983646274984857